[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "cd qd2",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "cd qd2 && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
