[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
    "cd qd2",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "cd qd2 && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
