[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
